$ cat Dockerfile_gitk
FROM centos:7.9.2009
RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
RUN sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
RUN yum install -y git gitk
RUN mkdir -pv /root/git/rancher/
RUN cd /root/git/rancher/ && git clone https://github.com/rancher/cli
WORKDIR /root/git/rancher/cli
CMD [ "gitk" ]
