services:
  myProject-build:
    build:
      args:
        apt_proxy: $apt_proxy
    image: myproject-dev-img:v0.0.1
    container_name: myProject-dev
#    volumes:
#      - ../src/myDIR/:/myDIR/
    network_mode: host
#    dns:
#      - 172.16.1.5
#      - 172.16.1.6
