FROM coreapps/ubuntu16.04:2024-11-24
ARG apt_proxy
RUN printf "Acquire::http::Proxy   \"$apt_proxy\";\nAcquire::https::Proxy   \"$apt_proxy\";\n" >  /etc/apt/apt.conf.d/00aptproxy
RUN sed -i 's|//archive|//fr.archive|' /etc/apt/sources.list
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt install -V -y vim git remake emacs-nox nano openssh-server bind9-host # ocaml-nox
RUN apt-get install -V -y command-not-found bash-completion ca-certificates openssh-client
RUN echo "source /usr/share/bash-completion/completions/git" >> $HOME/.profile
RUN mkdir -vm=700 $HOME/.ssh/
# Pour les instructions COPY et WORKDIR
ENV HOME /root
COPY ./config $HOME/.ssh/
COPY ./id_rsa $HOME/.ssh/
RUN mkdir $HOME/myDIR
WORKDIR $HOME
